// The timer's cue sounds, generated by scripts/generate-sounds.js. Played by
// hooks/useTimerCues.js, and by modules/round-bells in the background.
export const SOUND_SOURCES = {
  bell: require('../assets/sounds/bell.wav'),
  'bell-x3': require('../assets/sounds/bell-x3.wav'),
  clap: require('../assets/sounds/clap.wav'),
  beep: require('../assets/sounds/beep.wav'),
  'rest-warn': require('../assets/sounds/rest-warn.wav'),
};
