import { useEffect, useRef, useCallback } from 'react';
import { Vibration } from 'react-native';
import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';
import * as Speech from 'expo-speech';

// Generated by scripts/generate-sounds.js.
const SOURCES = {
  bell: require('../assets/sounds/bell.wav'),
  'bell-x3': require('../assets/sounds/bell-x3.wav'),
  clap: require('../assets/sounds/clap.wav'),
  beep: require('../assets/sounds/beep.wav'),
  'rest-warn': require('../assets/sounds/rest-warn.wav'),
};

// The recognizer ignores results this long after a bell, so our own bells never
// turn into commands. bell-x3 spans 0.64 s of strikes before the ring-out.
const ECHO_MS = { bell: 1500, 'bell-x3': 2150 };
// While TTS speaks (+0.5 s after it's done). The start estimate is generous;
// onDone extends the window if the line runs longer.
const SPEECH_TAIL_MS = 500;
const speechEstimateMs = (text) => 600 + text.length * 90;

const VIBRATION = { bell: 400, 'bell-x3': [0, 250, 70, 250, 70, 250] };

// Plays the timer's cues: preloaded bells/clap/beeps (expo-audio), spoken lines
// (expo-speech) and optional vibration. suppress(untilMs) is the voice
// recognizer's echo guard.
export function useTimerCues(suppress) {
  const playersRef = useRef(null);
  const suppressRef = useRef(suppress);
  suppressRef.current = suppress;

  useEffect(() => {
    // Duck the user's music under the bells; foreground only (v1).
    setAudioModeAsync({
      playsInSilentMode: true,
      interruptionMode: 'duckOthers',
      shouldPlayInBackground: false,
    }).catch(() => {});
    const players = {};
    for (const [name, source] of Object.entries(SOURCES)) players[name] = createAudioPlayer(source);
    playersRef.current = players;
    return () => {
      Speech.stop();
      Object.values(players).forEach(p => p.remove());
      playersRef.current = null;
    };
  }, []);

  const play = useCallback((name) => {
    const player = playersRef.current?.[name];
    if (!player) return;
    if (ECHO_MS[name]) suppressRef.current?.(Date.now() + ECHO_MS[name]);
    // play() doesn't rewind a finished sound, so seek to the start first.
    player.seekTo(0).then(() => player.play(), () => player.play());
  }, []);

  const say = useCallback((text) => {
    const hold = () => suppressRef.current?.(Date.now() + speechEstimateMs(text) + SPEECH_TAIL_MS);
    const release = () => suppressRef.current?.(Date.now() + SPEECH_TAIL_MS);
    hold();
    Speech.speak(text, {
      language: 'en-US',
      onStart: hold,
      onDone: release,
      onStopped: release,
      onError: release,
    });
  }, []);

  const vibrate = useCallback((name) => {
    Vibration.vibrate(VIBRATION[name] ?? 200);
  }, []);

  // cue: { atMs, sound?, say?, vibrate? } from utils/roundTimer buildCues().
  const fire = useCallback((cue) => {
    if (cue.sound) play(cue.sound);
    if (cue.vibrate) vibrate(cue.sound);
    if (cue.say) say(cue.say);
  }, [play, say, vibrate]);

  // "Test sounds" chips: a sound name, or 'voice'.
  const test = useCallback((name) => {
    if (name === 'voice') say('Round 1');
    else play(name);
  }, [play, say]);

  const stopSpeech = useCallback(() => Speech.stop(), []);

  return { fire, test, stopSpeech };
}
